version: '3.8'

volumes:
  maria:

services:

  # container PHP
  bookphp:
    container_name: phpbook
    build: 
      context: ./php
    ports:
      - '9000:9000'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
    depends_on:
      - bookbase

  # container nginx
  booknginx:
    container_name: nginxbook
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/symfo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookphp
      - bookbase
      - booknode

  # container de bdd en MARIADB
  bookbase:
    container_name: basebook
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: admin2024
      MYSQL_DATABASE: bookdata
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: book2024
    ports:
      - '3307:3306'
    volumes:
      - maria:/var/lib/mysql

  # container NODEJS
  booknode:
    container_name: nodebook
    build: 
      context: ./node
    volumes:
      - ./app:/var/www/symfo
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - bookphp
    tty: true
